# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 413bef3a4460da822f88a474c8786f8c5fecbf9fbb1ef6842323eaf56e5067e5914bac19c4b627f1998825b421cdc7e91f40ac30c2b6f4baf4bc0e3d990172c1

test:
  secret_key_base: 4822a73a38419bceef3484724fb7a768da4fdb2654d83fec899c1dd27997298e364338d33cad57b1399372e01c112ff7cd7c4da159cede71ded03006a92e64bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
